services:
  db:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    image: ${MARIADB_IMAGE:-wutthisak/app-data-center-db:latest}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_IMAGE:-wutthisak/app-data-center:latest}
