-- Step 1: Migrate existing INPUTTER and REVIEWER users to OPERATOR
UPDATE User SET role = 'INPUTTER' WHERE role = 'REVIEWER';

-- Step 2: Change the enum to replace INPUTTER with OPERATOR (MySQL requires recreating the enum)
ALTER TABLE User MODIFY role ENUM('ADMIN','INPUTTER','OPERATOR') NOT NULL DEFAULT 'INPUTTER';
UPDATE User SET role = 'OPERATOR' WHERE role = 'INPUTTER';
ALTER TABLE User MODIFY role ENUM('ADMIN','OPERATOR') NOT NULL DEFAULT 'OPERATOR';

-- Step 3: Add new profile fields
ALTER TABLE User ADD COLUMN position VARCHAR(191) NULL;
ALTER TABLE User ADD COLUMN department VARCHAR(191) NULL;
ALTER TABLE User ADD COLUMN email VARCHAR(191) NULL;
ALTER TABLE User ADD COLUMN phone VARCHAR(191) NULL;
ALTER TABLE User ADD COLUMN defaultShift VARCHAR(191) NULL;
